/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

import BookingCancelled from '#events/booking_cancelled'
import BookingDecided from '#events/booking_decided'
import BookingRequested from '#events/booking_requested'

export const events = {
  BookingCancelled: BookingCancelled,
  BookingDecided: BookingDecided,
  BookingRequested: BookingRequested,
}
