/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class BookingSchema extends BaseModel {
  static $columns = ['createdAt', 'endDate', 'id', 'startDate', 'updatedAt', 'userId', 'vehicleId'] as const
  $columns = BookingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare endDate: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare startDate: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare vehicleId: number | null
}

export class CommentSchema extends BaseModel {
  static $columns = ['content', 'createdAt', 'id', 'rating', 'updatedAt', 'userId', 'vehicleId'] as const
  $columns = CommentSchema.$columns
  @column()
  declare content: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare rating: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare vehicleId: number | null
}

export class MemorySchema extends BaseModel {
  static $columns = ['commentId', 'createdAt', 'id', 'path', 'updatedAt'] as const
  $columns = MemorySchema.$columns
  @column()
  declare commentId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare path: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PictureSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'path', 'title', 'updatedAt', 'vehicleId'] as const
  $columns = PictureSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare path: string | null
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vehicleId: number | null
}

export class TypeSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = TypeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['avatarPath', 'createdAt', 'email', 'firstName', 'id', 'isAdmin', 'lastName', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarPath: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare firstName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isAdmin: boolean | null
  @column()
  declare lastName: string | null
  @column({ serializeAs: null })
  declare password: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class VehicleSchema extends BaseModel {
  static $columns = ['animals', 'beds', 'city', 'cleanWater', 'createdAt', 'description', 'height', 'id', 'km', 'length', 'model', 'price', 'seats', 'travelAbroad', 'typeId', 'updatedAt', 'userId', 'wasteWater', 'width', 'year'] as const
  $columns = VehicleSchema.$columns
  @column()
  declare animals: boolean | null
  @column()
  declare beds: number | null
  @column()
  declare city: string | null
  @column()
  declare cleanWater: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare height: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare km: number | null
  @column()
  declare length: number | null
  @column()
  declare model: string | null
  @column()
  declare price: number | null
  @column()
  declare seats: number | null
  @column()
  declare travelAbroad: boolean | null
  @column()
  declare typeId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare wasteWater: number | null
  @column()
  declare width: number | null
  @column()
  declare year: number | null
}
